name=input("Please enter your name:")
age=int(input("Please enter your age:"))
city=input("Please enter your city name where you live:")
collegename=input("Please enter your college name where you studied:")
companyname=input("Please enter your company name:")
current_topic=input("Please enter your current learning Topic:")
year_experiance=float(input("Please enter your year of experiance:"))
python_liking=input("Do you like python or not?(True/False):")
python_liking=python_liking.lower()=='true'
expected_salary=int(input("Please enter your expected salary:"))

print("============User Entered Values for Variable=============")
print(f" Entered Variable name: {name} , Variable Type:",type(name))
print(f" Entered Variable name: {age} , Variable Type:",type(age))
print(f" Entered Variable city: {city} , Variable Type:",type(city))
print(f" Entered Variable collegename: {collegename} , Variable Type:",type(collegename))
print(f" Entered Variable companyname: {companyname}, Variable Type:",type(companyname))
print(f" Entered Variable current_topic:{current_topic}, Variable Type:",type(current_topic))
print(f" Entered Variable year_experiance: {year_experiance}, Variable Type:",type(year_experiance))
print(f" Entered Variable python_liking:{python_liking}, Variable Type:",type(python_liking))
print(f" Entered Variable expected_salary: {expected_salary}, Variable Type:",type(expected_salary))
